version: '3.8'

services:
  springboot-app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/studentdb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "Pspk#@123"
    volumes:
      - E:/Upload/:/app/uploads
    networks:
      - student-app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Pspk#@123"
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - student-app-network

volumes:
  mysql_data:

networks:
  student-app-network:
    driver: bridge
